theme: jekyll-theme-cayman
title: This is the hard coded title!!
description: The is the hard coded description for the hard coded title. 
tagline: This is the hard coded tagline only for trying out further changes
